token:
  expiration-time: 864000000
  secret: user_token_dev
gateway:
  ip: 192.168.0.45
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}d50293da496899188984006a4a157a8ce7f075a06f54b0377f6d2e75e8837aea'
